import { CollectionConfig } from "payload/types";
export const Employee: CollectionConfig = {
  slug: "employee",
  fields: [
    { name: "firstName", type: "text", required: true },
    { name: "middleName", type: "text", required: true },
    { name: "lastName", type: "text", required: true },
    {
      name: "sex",
      type: "text",
      required: true,
    },
    { name: "age", type: "text", required: true },
    { name: "educationLevel", type: "text", required: true },
    { name: "nationalId", type: "text", required: true },
    { name: "phoneNumber", type: "text", required: true },
    { name: "dateOfEmployement", type: "text", required: true },
    { name: "forensicRecordsUrls", type: "text", required: true },
    { name: "medicalExaminationUrls", type: "text", required: true },
    { name: "regionofemployment", type: "text", required: true },
    { name: "cityofemployment", type: "text", required: true },
    { name: "specificplaceofemployment", type: "text", required: true },
    { name: "employmentposition", type: "text", required: true },
    { name: "region", type: "text", required: true },
    { name: "zone", type: "text", required: true },
    { name: "woreda", type: "text", required: true },
    { name: "kebele", type: "text", required: true },
    { name: "houseNumber", type: "text", required: true },
    { name: "martialStatus", type: "text", required: true },
    { name: "getCoughtFirstName", type: "text", required: true },
    { name: "getCoughtMiddleName", type: "text", required: true },
    { name: "getCoughtLastName", type: "text", required: true },
    { name: "getCoughtRegion", type: "text", required: true },
    { name: "getCoughtZone", type: "text", required: true },
    { name: "getCoughtKebele", type: "text", required: true },
    { name: "getCoughtHouseNumber", type: "text", required: true },
    { name: "getCoughtNationalId", type: "text", required: true },
    { name: "getCoughtPhoneNumber", type: "text", required: true },
    {
      name: "status",
      type: "select",
      options: [
        { label: "Employeed", value: "employeed" },
        { label: "Free", value: "free" },
      ],
      defaultValue: "employeed",
    },
    {
      name: "activeAgent",
      type: "relationship",
      relationTo: "agents",
      hasMany: false,
    },
    {
      name: "prevAgents",
      type: "relationship",
      relationTo: "agents",
      required: true,
      hasMany: true,
    },
  ],
};
