/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    ordinaryUser: OrdinaryUser;
    applications: Application;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  middleName: string;
  lastName: string;
  nationalId: string;
  phoneNumber: string;
  sex: 'male' | 'female';
  role: 'screener' | 'manager' | 'admin';
  profile?: string | null;
  city: string;
  woreda: string;
  kebele: string;
  manager?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ordinaryUser".
 */
export interface OrdinaryUser {
  id: string;
  firstName: string;
  middleName: string;
  lastName: string;
  nationalId: string;
  phoneNumber: string;
  profile?: string | null;
  city: string;
  woreda: string;
  kebele: string;
  nationalIdVerified: 'pending' | 'approved' | 'denied';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  applier: string | OrdinaryUser;
  agentName: string;
  age: string;
  sex: 'male' | 'female';
  houseNumber: string;
  agentLogoUrl: {
    url?: string | null;
    id?: string | null;
  }[];
  statusAgentLogoUrl?: ('pending' | 'approved' | 'rejected') | null;
  profileUrl: {
    url?: string | null;
    id?: string | null;
  }[];
  statusProfileUrl?: ('pending' | 'approved' | 'rejected') | null;
  nationalIdUrls: {
    url?: string | null;
    id?: string | null;
  }[];
  statusNationalIdUrl?: ('pending' | 'approved' | 'rejected') | null;
  medicalUrls: {
    url?: string | null;
    id?: string | null;
  }[];
  statusMedicalUrl?: ('pending' | 'approved' | 'rejected') | null;
  educationalUrls: {
    url?: string | null;
    id?: string | null;
  }[];
  statusEducationalUrl?: ('pending' | 'approved' | 'rejected') | null;
  uniformDetailsUrls: {
    url?: string | null;
    id?: string | null;
  }[];
  statusUniformDetailUrl?: ('pending' | 'approved' | 'rejected') | null;
  employeeIdUrls: {
    url?: string | null;
    id?: string | null;
  }[];
  statusEmployeeIdUrl?: ('pending' | 'approved' | 'rejected') | null;
  responseOfScreener?: ('pending' | 'approved' | 'rejected') | null;
  responseOfManager?: ('pending' | 'approved' | 'rejected') | null;
  selectedScreener: string | User;
  selectedManager: string | User;
  rejectedDescriptions?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ordinaryUser';
        value: string | OrdinaryUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}